apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: atta 
  janus-idp.io/tekton: atta
  backstage.io/kubernetes-id: atta
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: atta
resources: 
- application-dev.yaml