apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: atta
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: atta 
  name: atta
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: atta 
